accuracy_dependencies_csv = readmatrix("../csv/accuracy_dependencies.csv");
A = readmatrix("../csv/matrix.csv");
eps = accuracy_dependencies_csv(:,1)';
errors_inf = accuracy_dependencies_csv(:,2)';
errors_2nd = accuracy_dependencies_csv(:,3)';
residuals_inf = accuracy_dependencies_csv(:,4)';
residuals_2nd = accuracy_dependencies_csv(:,5)';
iters = accuracy_dependencies_csv(:,6)';

figure
loglog(eps, errors_inf, "-b",...
       eps, errors_2nd, "--b",...
       eps, residuals_inf, "-r",...
       eps, residuals_2nd, "--r",...
       eps, eps, "-.b",...
       eps, norm(A, inf) * eps, "-.r");
title("Зависимости ошибки и невязки от точности")
xlabel("Точность \epsilon: ||x-x^*||_{\infty} < \epsilon")
legend("||x-x^*||_{\infty}",...
       "||x-x^*||_{2}",...
       "||Ax-b||_{\infty}",...
       "||Ax-b||_{2}",...
       "Максимально допустимая ошибка \epsilon",...
       "Максимально допустимая невязка ||A||_{\infty}\cdot \epsilon",...
       'Location', 'southeast')
grid on

figure
semilogx(eps, iters)
title("Зависимость количества итераций от точности")
xlabel("Точность \epsilon: ||x-x^*||_{\infty} < \epsilon")
ylabel("Количество итераций")
grid on
