x0_dependencies_csv = readmatrix("../csv/x0_dependencies.csv");
A = readmatrix("../csv/matrix.csv");
x0x_inf = x0_dependencies_csv(:, 1)';
x0x_2nd = x0_dependencies_csv(:, 2)';
errors_inf = x0_dependencies_csv(:,3)';
errors_2nd = x0_dependencies_csv(:,4)';
residuals_inf = x0_dependencies_csv(:,5)';
residuals_2nd = x0_dependencies_csv(:,6)';
iters = x0_dependencies_csv(:,7)';

figure
%subplot(1, 2, 1)
loglog(x0x_inf, errors_inf, "-b",...
       x0x_inf, errors_2nd, "--b",...
       x0x_inf, residuals_inf, "-r",...
       x0x_inf, residuals_2nd, "--r",...
       x0x_inf, zeros([1 length(x0x_inf)]) + 1e-8, "-.b",...
       x0x_inf, norm(A, inf) * (zeros([1 length(x0x_inf)]) + 1e-8), "-.r");
title("Зависимости ошибки и невязки от начального приближения")
xlabel("||x^{(0)}-x^*||_{\infty}")
legend("||x-x^*||_{\infty}",...
       "||x-x^*||_{2}",...
       "||Ax-b||_{\infty}",...
       "||Ax-b||_{2}",...
       "Максимально допустимая ошибка \epsilon",...
       "Максимально допустимая невязка ||A||_{\infty}\cdot \epsilon",...
       'Location', 'northwest')
grid on

%{
subplot(1, 2, 2)
loglog(x0x_2nd, errors_inf, "-b",...
       x0x_2nd, errors_2nd, "--b",...
       x0x_2nd, residuals_inf, "-r",...
       x0x_2nd, residuals_2nd, "--r",...
       x0x_2nd, zeros([1 length(x0x_2nd)]) + 1e-8, "-.b",...
       x0x_2nd, norm(A, inf) * (zeros([1 length(x0x_2nd)]) + 1e-8), "-.r");
title("Зависимости ошибки и невязки от начального приближения")
xlabel("||x^{(0)}-x^*||_{2}")
legend("||x-x^*||_{\infty}",...
       "||x-x^*||_{2}",...
       "||Ax-b||_{\infty}",...
       "||Ax-b||_{2}",...
       "Максимально допустимая ошибка \epsilon",...
       "Максимально допустимая невязка ||A||_{\infty}\cdot \epsilon",...
       'Location', 'northwest')
grid on
%}

figure
semilogx(x0x_inf, iters)
title("Зависимость количества итераций от начального приближения")
xlabel("||x^{(0)}-x^*||_{\infty}")
ylabel("Количество итераций")
grid on